### ISSUE TITLE
Outercore marketing to-do

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#41]
- [ ] Emily Lukas - https://www.notion.so/pl-strflt/Content-plan-0f0a480738ce494a9d0c97270799fe38
- [ ] user facing Technical features launch - https://github.com/bacalhau-project/bacalhau/issues/2179
- [ ] Target audience - web3 developers
- [ ] What you trying to achieve - CTA - GitHub stars is not enough, increase adoption - 
- [ ] fill out Emily s form  
- [ ] Target audience, who you want to use it
- [ ] usp: why should use it 
- [ ] examples: DeSci project save 40% cost by using stable API

wait for Niki hackathons:
- [ ] Chainlink hackathon
- [ ] FVM despost bacalhau bounty

Potential marketing collaborations: 
Newsletter Inclusion 
Hackernoon submission
Filecoin into hn
Twitter thread
